{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubexray.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubexray.name" . }}
    helm.sh/chart: {{ include "kubexray.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  xray_config.yaml: |-
    {{ .Values.xrayConfig }}
{{- end -}}
